DEFAULT_TEMPORAL_ADDRESS = "127.0.0.1:7233"
DEFAULT_TEMPORAL_NAMESPACE = "default"
DEFAULT_TEMPORAL_TASK_QUEUE = "sec-review-agents"
DEFAULT_WORKFLOW_TIMEOUT_SECONDS = 3 * 60 * 60


__all__ = [
    "DEFAULT_TEMPORAL_ADDRESS",
    "DEFAULT_TEMPORAL_NAMESPACE",
    "DEFAULT_TEMPORAL_TASK_QUEUE",
    "DEFAULT_WORKFLOW_TIMEOUT_SECONDS",
]
